# Generated by Django 3.0.6 on 2020-05-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('psw', models.CharField(max_length=10)),
                ('pswr', models.CharField(max_length=10)),
            ],
        ),
    ]
